In [ ]:
import torch
import torch.nn as nn


In [ ]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out


class Model2(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out


In [ ]:
# Create dataset
features = torch.rand(10, 5)
# Create model
model = Model(features.shape[1])

# call model for forward pass
model(features)


tensor([[0.4027],
        [0.4101],
        [0.4823],
        [0.4526],
        [0.4615],
        [0.3472],
        [0.4049],
        [0.4270],
        [0.4559],
        [0.3325]], grad_fn=<SigmoidBackward0>)

In [ ]:
model2 = Model2(features.shape[1])
model2(features)


tensor([[0.4323],
        [0.4113],
        [0.4450],
        [0.4273],
        [0.4186],
        [0.4083],
        [0.4461],
        [0.4425],
        [0.4356],
        [0.4180]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight


Parameter containing:
tensor([[ 0.0784,  0.1559, -0.3025, -0.1940,  0.2071]], requires_grad=True)

In [ ]:
model2.linear1.weight


Parameter containing:
tensor([[ 0.2403, -0.1077, -0.3423,  0.3309,  0.3286],
        [ 0.3746, -0.0814, -0.0326, -0.1182, -0.2884],
        [-0.3608, -0.1797,  0.2152, -0.1401, -0.4097]], requires_grad=True)

In [8]:
!pip install torchinfo


In [ ]:
from torchinfo import summary


In [ ]:
summary(model, input_size=(10, 5))


Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
summary(model2, input_size=(10, 5))


Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Sequential Model/container


In [ ]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3), nn.ReLU(), nn.Linear(3, 1), nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out


In [ ]:
model3 = Model(features.shape[1])


In [ ]:
summary(model3, input_size=(10, 5))


Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
model3


Model(
  (network): Sequential(
    (0): Linear(in_features=5, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)