In [ ]:
import torch
print(torch.__version__)

2.8.0+cpu


In [ ]:
if torch.cuda.is_available():
    print('GPU')
    print(f'using gpu: {torch.cuda.get_device_name(0)}')
else:
    print('CPU')

CPU


## Creating a tensor

In [ ]:
torch.empty(3,32,32)

tensor([[[ 1.5695e-43,  0.0000e+00,  3.8709e-04,  ...,  0.0000e+00,
           4.1927e-04,  0.0000e+00],
         [ 4.1928e-04,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           3.3631e-44,  1.1210e-44],
         [ 1.6388e-38,  0.0000e+00,  1.4013e-45,  ...,  2.2421e-44,
           3.3631e-44,  1.8217e-44],
         ...,
         [ 1.4013e-45,  2.2421e-44,  1.4714e-43,  ...,  7.8473e-44,
           1.7516e-43,  9.6690e-44],
         [ 2.9427e-44,  0.0000e+00,  3.8720e-04,  ...,  0.0000e+00,
           3.8719e-04,  0.0000e+00],
         [ 1.5863e-42,  4.4319e-41,  3.8720e-04,  ...,  0.0000e+00,
           3.8721e-04,  0.0000e+00]],

        [[ 1.5456e-42,  0.0000e+00,  3.8720e-04,  ...,  0.0000e+00,
           1.5821e-42,  0.0000e+00],
         [ 1.7516e-43,  2.2421e-44,  1.7516e-43,  ...,  0.0000e+00,
           1.9898e-43,  0.0000e+00],
         [ 3.8721e-04,  0.0000e+00,  1.6549e-42,  ...,  0.0000e+00,
           1.9898e-43,  2.2421e-44],
         ...,
         [ 1.5456e-42,  2

In [ ]:
torch.rand(4,4)

tensor([[0.1762, 0.4635, 0.3567, 0.5068],
        [0.1551, 0.6346, 0.6822, 0.0480],
        [0.9523, 0.2058, 0.9476, 0.2228],
        [0.8825, 0.6965, 0.2151, 0.6173]])

In [ ]:
torch.manual_seed(100)
torch.rand(4,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183, 0.9014]])

In [ ]:
torch.tensor([(4,5,6), (5,6,7)])

tensor([[4, 5, 6],
        [5, 6, 7]])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.linspace(5,6,5)

tensor([5.0000, 5.2500, 5.5000, 5.7500, 6.0000])

In [ ]:
torch.eye(5,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:

torch.ones(5,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:

torch.ones(5,5)*4

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])

In [ ]:
torch.full((5,5), 4)

tensor([[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]])

In [ ]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
x.shape

torch.Size([2, 4])

In [ ]:
torch.empty_like(x)

tensor([[      943358880, 135836351212560,               1,               8],
        [              0,               0,               0,               0]])

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.9969, 0.7565, 0.2239, 0.3023],
        [0.1784, 0.8238, 0.5557, 0.9770]])

##Mathmatical Operations

###Scaler Operations

In [ ]:
x+2

tensor([[ 3,  4,  5,  6],
        [ 7,  8,  9, 10]])

In [ ]:
x-2

tensor([[-1,  0,  1,  2],
        [ 3,  4,  5,  6]])

In [ ]:
x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [ ]:
x//2

tensor([[0, 1, 1, 2],
        [2, 3, 3, 4]])

In [ ]:
x**3

tensor([[  1,   8,  27,  64],
        [125, 216, 343, 512]])

In [ ]:
a  = torch.rand(4,4)
b  = torch.rand(4,4)

In [ ]:
a*b

tensor([[0.0261, 0.1519, 0.1353, 0.1406],
        [0.7395, 0.0328, 0.0158, 0.1472],
        [0.1114, 0.6743, 0.1811, 0.3605],
        [0.2917, 0.3995, 0.2040, 0.1043]])

In [ ]:
a-b

tensor([[ 0.7328, -0.7498,  0.1314, -0.4027],
        [ 0.0658, -0.6096,  0.0893, -0.1879],
        [-0.3994,  0.1846, -0.6366, -0.5155],
        [ 0.1169, -0.5201,  0.1320,  0.1676]])

In [ ]:
a==b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
a*b

tensor([[0.0261, 0.1519, 0.1353, 0.1406],
        [0.7395, 0.0328, 0.0158, 0.1472],
        [0.1114, 0.6743, 0.1811, 0.3605],
        [0.2917, 0.3995, 0.2040, 0.1043]])

In [ ]:
a**b

tensor([[0.9910, 0.1930, 0.7763, 0.3917],
        [0.9110, 0.1383, 0.8580, 0.5560],
        [0.3753, 0.9396, 0.2689, 0.4296],
        [0.7817, 0.4445, 0.7761, 0.8039]])

In [ ]:
a.abs()

tensor([[0.7668, 0.1659, 0.4393, 0.2243],
        [0.8935, 0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224, 0.4175]])

In [ ]:
a.neg()

tensor([[-0.7668, -0.1659, -0.4393, -0.2243],
        [-0.8935, -0.0497, -0.1780, -0.3011],
        [-0.1893, -0.9186, -0.2131, -0.3957],
        [-0.6017, -0.4234, -0.5224, -0.4175]])

In [ ]:
a.round()

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 1., 0.]])

In [ ]:
torch.round(a)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 1., 0.]])

In [ ]:
torch.ceil(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:

torch.floor(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.clamp(a, min=0.5, max=0.7)

tensor([[0.7000, 0.5000, 0.5000, 0.5000],
        [0.7000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.7000, 0.5000, 0.5000],
        [0.6017, 0.5000, 0.5224, 0.5000]])

###Reduction Operations

In [ ]:
e = torch.randint(0,10,(4,4), dtype=torch.float32)
e

tensor([[5., 1., 0., 0.],
        [2., 2., 3., 7.],
        [1., 5., 0., 2.],
        [3., 7., 0., 2.]])

In [ ]:
torch.sum(e)

tensor(40.)

In [ ]:
torch.sum(e, dim=0)

tensor([11., 15.,  3., 11.])

In [ ]:


torch.sum(e, dim=0)

tensor([11., 15.,  3., 11.])

In [ ]:

torch.mean(e)
torch.mean(e, dim=1)


tensor([1.5000, 3.5000, 2.0000, 3.0000])

In [ ]:

torch.median(e, dim=1)

torch.return_types.median(
values=tensor([0., 2., 1., 2.]),
indices=tensor([3, 1, 0, 3]))

In [ ]:
torch.max(e)

tensor(7.)

In [ ]:
torch.min(e)

tensor(0.)

In [ ]:
torch.std(e)

tensor(2.3664)

In [ ]:
torch.var(e)

tensor(5.6000)

In [ ]:
torch.argmax(e)

tensor(7)

In [ ]:
torch.argmin(e)

tensor(2)

In [ ]:
e.sub_(x)

###Tensor Operation on GPU


In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
torch.rand((2,3), device=device)

tensor([[0.9366, 0.7651, 0.0416],
        [0.4357, 0.8844, 0.0648]], device='cuda:0')

In [ ]:
a = torch.rand((2,3))

In [ ]:
a

tensor([[0.2959, 0.8662, 0.9792],
        [0.2813, 0.3666, 0.3559]])

In [ ]:
a_gpu = a.to(device=device)

In [ ]:
import numpy as np
a = torch.tensor([1,2,3])

a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,4])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 4])

In [ ]:
import time
# Define the size of the matrices
size = 10000 # Large size for performance comparison
# Create random matrices on CPU
matrix_cpul = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)
# measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpul, matrix_cpu2)
cpu_time = time.time()
cpu_time = time.time() - start_time
print(f"Time on CPU: {cpu_time:.4f} seconds")
# Move matrices to GPIJ
matrix_gpul = matrix_cpul.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')
# measure time on GPU
start_time = time. time()
result_gpu = torch.matmul(matrix_gpul, matrix_gpu2)
# Matrix multiplication on CPU
# Matrix multiplication on GPU
torch. cuda.synchronize()
gpu_time = time.time() - start_time # Ensure all GPU operations are complete

print(f"Time on GPIJ: {gpu_time:.4f} seconds")
# Compare results
print("\nSpeedup (CPU time / GPU time):" , cpu_time / gpu_time)

Time on CPU: 6.0384 seconds


AssertionError: Torch not compiled with CUDA enabled